### ISSUE TITLE
About the implementation of the off policy corrections

### ISSUE THREAD

**Issue by zhkmxx9302013** [bhairavmehta95/data-efficient-hrl#1]
Thanks for providing the code of  HIRO.
I‘ve got a question about the implementation of the off-policy corrections function.
What does this comment `# TODO: Doesn't include subgoal transitions!!` mean, and why this function return the subgoal directly, is there anything wrong with the sampling of the candidate goal? Thanks for asking :).

![1](https://res.cloudinary.com/djhkiiiap/image/upload/v1554105720/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20190401155604.png)

**Comment by smalltingting** [comment]
> Thanks for providing the code of HIRO.
> I‘ve got a question about the implementation of the off-policy corrections function.
> What does this comment `# TODO: Doesn't include subgoal transitions!!` mean, and why this function return the subgoal directly, is there anything wrong with the sampling of the candidate goal? Thanks for asking :).
> 
> ![1](https://camo.githubusercontent.com/8b2f6904b2324d01a88acb6c1ea0c04b1a08cfee/68747470733a2f2f7265732e636c6f7564696e6172792e636f6d2f646a686b69696961702f696d6167652f75706c6f61642f76313535343130353732302f2545352542452541452545342542462541312545362538382541412545352539422542455f32303139303430313135353630342e706e67)

I have the same problem with you. Have you solved it?

**Comment by bhairavmehta95** [comment]
Oh man - I never even saw this :( I apologize.

> What does this comment # TODO: Doesn't include subgoal transitions!! mean, 

So when I open sourced this code, I was actually working in a slightly different domain (images, not states) so Equation 2 in this code was never implemented (since Eq2 of subgoal transitions doesn't make sense in a latent space) So, to use this correctly, you'd have to actually transition the subgoal in the main loop.

![Screen Shot 2019-06-19 at 3 57 08 PM](https://user-images.githubusercontent.com/10503729/59796220-fee49680-92aa-11e9-8d67-afb7f2773171.png)


> and why this function return the subgoal directly, is there anything wrong with the sampling of the candidate goal? 

Nope; Because I didn't add the above, I just added the subgoals directly. But, if we add the above, it works fine.

**Comment by zhkmxx9302013** [comment]
> Oh man - I never even saw this :( I apologize.
> 
> > What does this comment # TODO: Doesn't include subgoal transitions!! mean,
> 
> So when I open sourced this code, I was actually working in a slightly different domain (images, not states) so Equation 2 in this code was never implemented (since Eq2 of subgoal transitions doesn't make sense in a latent space) So, to use this correctly, you'd have to actually transition the subgoal in the main loop.
> 
> ![Screen Shot 2019-06-19 at 3 57 08 PM](https://user-images.githubusercontent.com/10503729/59796220-fee49680-92aa-11e9-8d67-afb7f2773171.png)
> 
> > and why this function return the subgoal directly, is there anything wrong with the sampling of the candidate goal?
> 
> Nope; Because I didn't add the above, I just added the subgoals directly. But, if we add the above, it works fine.

ok, thanks for your comment~
