### ISSUE TITLE
what is 'run_nopt' in your implementation 'main.py'?

### ISSUE THREAD

**Issue by RushToNeverLand** [bhairavmehta95/data-efficient-hrl#5]

**Comment by peasant98** [comment]
It doesn't seem to exist.

**Comment by RushToNeverLand** [comment]
https://github.com/bhairavmehta95/data-efficient-hrl/blob/9260499dccfa5a9c0fd1e65320b426540653f4ac/main.py#L84
So it seems like a personal test and not committed to public repo.
